vulnerabilities:
  - id: CVE-2026-33811
    statement: waiting for kubectl release
    expired_at: 2026-09-01
    paths:
      - usr/bin/kubectl
  - id: CVE-2026-33814
    statement: waiting for kubectl release
    expired_at: 2026-09-01
    paths:
      - usr/bin/kubectl
  - id: CVE-2026-39820
    statement: waiting for kubectl release
    expired_at: 2026-09-01
    paths:
      - usr/bin/kubectl
  - id: CVE-2026-39836
    statement: waiting for kubectl release
    expired_at: 2026-09-01
    paths:
      - usr/bin/kubectl
  - id: CVE-2026-42499
    statement: waiting for kubectl release
    expired_at: 2026-09-01
    paths:
      - usr/bin/kubectl
