vulnerabilities:
  - id: CVE-2026-33811
    paths:
      - usr/bin/kubectl
    statement: Wait for a new kubectl-Release
    expired_at: 2026-07-01
  - id: CVE-2026-33814
    paths:
      - usr/bin/kubectl
    statement: Wait for a new kubectl-Release
    expired_at: 2026-07-01
  - id: CVE-2026-39820
    paths:
      - usr/bin/kubectl
    statement: Wait for a new kubectl-Release
    expired_at: 2026-07-01
  - id: CVE-2026-39836
    paths:
      - usr/bin/kubectl
    statement: Wait for a new kubectl-Release
    expired_at: 2026-07-01
  - id: CVE-2026-42499
    paths:
      - usr/bin/kubectl
    statement: Wait for a new kubectl-Release
    expired_at: 2026-07-01
